# Generated by Django 3.2.3 on 2021-10-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('upload', models.ImageField(upload_to='uploads/')),
                ('address', models.TextField(max_length=150)),
                ('mobile', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=120)),
            ],
        ),
    ]
