# Generated by Django 3.2.3 on 2021-10-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_project', '0002_auto_20211003_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='upload',
        ),
    ]
